#!/bin/bash

# Cleaning
sudo sed -i '/# columndeeply\'s hosts list/,$d' /etc/hosts

# Cloning
git clone https://github.com/columndeeply/hosts.git

# Merging
echo "# columndeeply's hosts list" | sudo tee -a /etc/hosts
cat /home/artix/hosts/hosts00 /home/artix/hosts/hosts01 /home/artix/hosts/hosts02 /home/artix/hosts/hosts03 /home/artix/hosts/hosts04 | sudo tee -a /etc/hosts
echo "# END columndeeply's hosts list" | sudo tee -a /etc/hosts

# Deleting
rm -rf
